dafault:
	g++ -std=c++20 -O0 -Wall -Wpedantic experiments/uhr_sa_pattern.cpp -o uhr_sa_pattern
	./uhr_sa_pattern result.csv 128 10000 100000 10000
	g++ -std=c++20 -O0 -Wall -Wpedantic experiments/uhr_salcp_pattern.cpp -o uhr_salcp_pattern
	./uhr_salcp_pattern result.csv 128 10000 100000 10000